version: "2"
services: 
  web-api: 
    build: ./web-api
    ports: 
      - "8080:8080"
    container_name: web-api
  kafka-batcher: 
    build: ./kafka-batcher
    container_name: kafka-batcher
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
