FROM openjdk:8-jdk-alpine
RUN mkdir /app
WORKDIR /app
RUN mkdir /data
COPY target/batched-file-creator-0.0.1.jar batched-file-creator-0.0.1.jar
COPY application-docker.properties application.properties
ENTRYPOINT ["java","-jar","/app/batched-file-creator-0.0.1.jar", "-Dspring.config.location=/app/application.properties"]